/**
 * Generate a VAPID keypair for web-push.
 *
 * Usage:
 *   npx ts-node scripts/generate-vapid.ts
 *
 * Output goes to stdout — copy the three lines into your .env / Railway vars.
 */
import webpush from 'web-push';

const keys = webpush.generateVAPIDKeys();

console.log('# Generated by scripts/generate-vapid.ts');
console.log(`VAPID_PUBLIC_KEY=${keys.publicKey}`);
console.log(`VAPID_PRIVATE_KEY=${keys.privateKey}`);
console.log('VAPID_SUBJECT=mailto:admin@lumalab.asia');
console.log('');
console.log('# Public key (also exposed via GET /api/v1/push/public-key):');
console.log(keys.publicKey);
